// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User_API.Data;

#nullable disable

namespace User_API.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User_API.Models.TempUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("NameEN")
                        .HasColumnType("text");

                    b.Property<string>("NameJP")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TempUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 10,
                            NameEN = "Ash",
                            NameJP = "Satoshi"
                        },
                        new
                        {
                            Id = 2,
                            Age = 9,
                            NameEN = "Misty",
                            NameJP = "Kasumi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
