// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User_API.Data;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20250717104223_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pikachu",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zapdosh",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charizard",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Arcaine",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rapidash",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Weedle",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Venomoth",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Metapod",
                            Type = "Bug"
                        });
                });

            modelBuilder.Entity("User_API.Models.TempUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("NameEN")
                        .HasColumnType("text");

                    b.Property<string>("NameJP")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TempUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 10,
                            NameEN = "Ash",
                            NameJP = "Satoshi"
                        },
                        new
                        {
                            Id = 2,
                            Age = 11,
                            NameEN = "Misty",
                            NameJP = "Kasumi"
                        },
                        new
                        {
                            Id = 3,
                            Age = 11,
                            NameEN = "Brock",
                            NameJP = "Takeshi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
