/**
 * User API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pokemon } from './pokemon';


export interface User { 
    id?: number;
    nameEN?: string | null;
    nameJP?: string | null;
    age?: number;
    pokemons?: Array<Pokemon> | null;
}

