/**
 * Pokemon API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PokemonDto { 
    name?: string | null;
    type?: string | null;
}

